server:
  port: 6060
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2020/eureka/eureka/, http://eureka2:4040/eurekas/eureka/
  instance:
    prefer-ip-address: true


spring:
  application:
    name: ribbon-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test3?serverTimezone=UTC
    password: root
    username: root
  main:
    allow-bean-definition-overriding: true