server:
  port: 7070

spring:
  application:
    name: zuul-server
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2020/eureka/eureka/

zuul:
  routes:
    user-server: /u/**
